--caso 1
--Un trabajador pertenece a un departamento.
--El trabajador tiene un nombre, rut y dirección.
--El departamento tiene un nombre.
--Un trabajador posee liquidaciones.
--La liquidación se guarda en un archivo drive
